trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: DownloadSecureFile@1
    name: keystore
    inputs:
      secureFile: 'camperguru.keystore'

  - task: DownloadSecureFile@1
    name: keystoreProps
    inputs:
      secureFile: 'camperguru-keystore.properties'

  - script: |
      mkdir output
      cp "$(keystore.secureFilePath)" output/
      cp "$(keystoreProps.secureFilePath)" output/
    displayName: 'Copy secure files to output folder'

  - publish: output
    artifact: secure-files
